# Generated by Django 3.2 on 2022-07-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='image',
            field=models.ManyToManyField(blank=True, to='blogs.Images'),
        ),
    ]
