# Generated by Django 3.2 on 2022-07-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_images_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='caption',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
